on: push


jobs:
  flask-run:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
#      - run: pip3 list
      - run: pip3 install flask
      - run: python3 app.py
      - run: curl http://127.0.0.1:5000

